name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: keplerdev.azurecr.io
        username: ${{ secrets.CR_KEPLERDEV_USERNAME }}
        password: ${{ secrets.CR_KEPLERDEV_PASSWORD }}
    
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag keplerdev.azurecr.io/${{ secrets.IMAGENAME }}:latest
        
    - name: Push the tagged Docker image
      run: docker push keplerdev.azurecr.io/${{ secrets.IMAGENAME }}:latest
